FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Build aplikasi
RUN npm run build

# Expose port
EXPOSE 3002

# Development mode - watch for changes
CMD ["npm", "run", "dev"]
